const S={c:+localStorage.lixC||250,x:+localStorage.lixX||0,e:+localStorage.lixE||10,l:+localStorage.lixL||1,m:JSON.parse(localStorage.lixM||"[]")};const $=s=>document.querySelector(s);
function save(){localStorage.lixC=S.c;localStorage.lixX=S.x;localStorage.lixE=S.e;localStorage.lixL=S.l;localStorage.lixM=JSON.stringify(S.m)}
function render(){$("#coins").textContent=S.c;$("#xp").textContent=S.x;$("#energy").textContent=S.e;$("#level").textContent=S.l;$("#cityLevel").textContent=S.l}
function xp(n){S.x+=n;while(S.x>=500*S.l){S.x-=500*S.l;S.l++}save();render()}
function coin(n){S.c+=n;save();render()}
function energy(){if(S.e<1){alert("No Energy");return false}S.e--;save();render();return true}
const ms=["🎯 Play Lix Target","🏃 Play Lix Runner","🐾 Feed & play with Pet","🪙 Collect 100 Coins","🏠 Visit Lix House"],rv=[50,50,75,60,40];
$("#missions").innerHTML=ms.map((m,i)=>`<div class="mission"><span>${m}</span><button data-m="${i}">+${rv[i]} XP</button></div>`).join("");
document.querySelectorAll("[data-m]").forEach(b=>b.onclick=()=>{let i=+b.dataset.m;if(S.m.includes(i))return;S.m.push(i);b.classList.add("done");b.textContent="DONE";xp(rv[i])});
function modal(h){$("#content").innerHTML=h;$("#modal").classList.remove("hidden")}$("#close").onclick=()=>$("#modal").classList.add("hidden");
document.querySelectorAll(".game").forEach(b=>b.onclick=()=>game(b.dataset.game));
function game(g){if(!energy())return;if(g==="target"){modal(`<h2>🎯 Lix Target</h2><p>Hit 5 targets.</p><div class="area" id="a"></div><b id="h">0/5</b>`);let h=0;function p(){a.innerHTML='<button class="target" id="t"></button>';t.style.left=Math.random()*75+10+"%";t.style.top=Math.random()*65+10+"%";t.onclick=()=>{h++;$("#h").textContent=h+"/5";if(h>=5){coin(50);xp(40);modal("<h2>🎉 Great!</h2><p>+50 Coins • +40 XP</p><button class='action' onclick='document.querySelector(\"#modal\").classList.add(\"hidden\")'>Continue</button>")}else p()}}p()}else if(g==="runner"){modal(`<h2>🏃 Lix Runner</h2><p>Tap JUMP to survive 300m.</p><div class="area"><div style="position:absolute;bottom:0;width:100%;height:35%;background:#d3dbe4"></div><div style="position:absolute;bottom:30px;left:25px;font-size:50px">🤖</div><div id="o" style="position:absolute;bottom:30px;right:20px;font-size:35px">🧱</div></div><button class="action" id="j">JUMP</button><p><b id="d">0</b> m</p>`);let d=0;let z=setInterval(()=>{d+=25;$("#d").textContent=d;if(d>=300){clearInterval(z);coin(60);xp(50);modal("<h2>🏁 Finished!</h2><p>+60 Coins • +50 XP</p><button class='action' onclick='document.querySelector(\"#modal\").classList.add(\"hidden\")'>Continue</button>")}},500);$("#j").onclick=()=>{o.style.opacity=o.style.opacity==="0"?1:0;setTimeout(()=>o.style.opacity=1,220)}}else{modal(`<h2>🪙💣 Catch & Bomb</h2><p>Collect coins.</p><div class="area" style="display:flex;align-items:center;justify-content:center;gap:18px;font-size:50px"><button id="c1">🪙</button>💣<button id="c2">🪙</button></div><p>Collected: <b id="cc">0</b></p><button class="action" id="f">Finish Round</button>`);let c=0;function add(){c+=10;$("#cc").textContent=c}c1.onclick=add;c2.onclick=add;f.onclick=()=>{coin(c);xp(60);modal(`<h2>🎉 Round complete</h2><p>+${c} Coins • +60 XP</p><button class="action" onclick='document.querySelector("#modal").classList.add("hidden")'>Continue</button>`)}}}
render();