const KEY="lixcity_v04";
const defaults={level:1,xp:0,coins:250,tickets:0,energy:10,maxEnergy:10,house:1,pet:1,petPlayed:0,lastSpin:0,game:{target:1,runner:1,catch:1},missions:[{t:"Play any game",xp:40,done:false},{t:"Earn 50 Coins",xp:40,done:false},{t:"Finish Lix Target",xp:50,done:false},{t:"Feed & play with your Pet",xp:50,done:false},{t:"Visit your City",xp:30,done:false}]};
let S=JSON.parse(localStorage.getItem(KEY)||"null")||structuredClone(defaults);
function save(){localStorage.setItem(KEY,JSON.stringify(S))}
function need(l){return Math.round(500*l+300*Math.pow(Math.max(0,l-1),1.35))}
function addXP(n){S.xp+=n;while(S.xp>=need(S.level)){S.xp-=need(S.level);S.level++;S.house=S.level;toast("🏠 House / Player Level "+S.level+"!")}save();render()}
function spend(n){if(S.coins<n){toast("Not enough Coins");return false}S.coins-=n;save();return true}
function useEnergy(){if(S.energy<1){toast("⚡ No Energy");return false}S.energy--;save();render();return true}
function coins(n){S.coins+=n;save();render()}
function toast(t){const e=document.querySelector(".toast");if(!e)return;e.textContent=t;e.style.display="block";clearTimeout(window.tt);window.tt=setTimeout(()=>e.style.display="none",1800)}
function nav(a){return `<div class="nav"><div class="navin">
<button class="${a==="home"?"active":""}" onclick="show('home')"><b>🏠</b>Home</button><button class="${a==="city"?"active":""}" onclick="show('city')"><b>🏙️</b>City</button><button class="${a==="games"?"active":""}" onclick="show('games')"><b>🎮</b>Games</button><button class="${a==="pets"?"active":""}" onclick="show('pets')"><b>🐾</b>Pets</button><button class="${a==="more"?"active":""}" onclick="show('more')"><b>☰</b>More</button></div></div>`}
function shell(c,a){document.getElementById("app").innerHTML=`<header class="top"><div class="brand"><img src="cellix-logo.webp"></div><div class="stats"><span>⭐ ${S.xp}</span><span>🪙 ${S.coins}</span><span>⚡ ${S.energy}/${S.maxEnergy}</span></div></header><main class="wrap">${c}</main>${nav(a)}<div class="toast"></div>`}
function show(p){({home,city,games,pets,more}[p])()}
function home(){const n=need(S.level),pct=Math.min(100,S.xp/n*100);shell(`<section class="hero"><div><small>LIX CITY</small><h1>Welcome to your city</h1><p>PLAY → EARN → BUILD → PROGRESS</p><div class="level">HOUSE / PLAYER LEVEL <strong>${S.level}</strong></div></div><img src="lix.png"></section>
<section class="card"><div class="title"><h2>🏙️ My City</h2><small>House Lv. ${S.house}</small></div><div class="grid"><div class="tile"><div>🏠</div><h3>Lix House</h3><small>Level ${S.house}</small></div><div class="tile ${S.level<2?"locked":""}"><div>🎮</div><h3>Game Center</h3><small>${S.level<2?"Unlock Lv. 2":"Available"}</small></div><div class="tile ${S.level<4?"locked":""}"><div>🏪</div><h3>Cellix Store</h3><small>${S.level<4?"Unlock Lv. 4":"Available"}</small></div><div class="tile"><div>🛣️</div><h3>City Road</h3><small>Starting area</small></div></div></section>
<section class="card"><div class="title"><h2>📈 Progress</h2><b>Lv. ${S.level}</b></div><div class="progress"><div class="bar" style="width:${pct}%"></div></div><p>${S.xp} / ${n} XP to next level</p><div class="row"><button class="btn" onclick="show('games')">🎮 Play</button><button class="btn alt" onclick="show('city')">🏙️ Build City</button></div></section>
<section class="card"><div class="title"><h2>📋 Daily Missions</h2><small>5 missions</small></div>${S.missions.map((m,i)=>`<div class="mission"><span>${m.done?"✅":"⬜"} ${m.t} <small>+${m.xp} XP</small></span>${m.done?"":"<button class='btn alt' onclick='claimMission("+i+")'>Claim</button>"}</div>`).join("")}</section>`,"home")}
function claimMission(i){if(S.missions[i].done)return;S.missions[i].done=true;addXP(S.missions[i].xp);toast("Mission complete! +"+S.missions[i].xp+" XP")}
function city(){shell(`<section class="card"><div class="title"><h2>🏙️ Lix City</h2><small>House Lv. ${S.house}</small></div><div class="tile center"><img src="lix.png" style="width:115px"><h2>Your city grows with Lix.</h2><p>New buildings unlock as your House / Player Level increases.</p></div></section>
<section class="card"><div class="title"><h2>🔓 Building Roadmap</h2></div><div class="grid">${[["🏠","Lix House",1],["🎮","Game Center",2],["🏪","Cellix Store",4],["🌳","Lix Park",7],["⚡","Energy Station",8],["🛠️","Lix Workshop",12],["🏬","Lix Market",15],["🎨","Lix Studio",18],["🐾","Lix Stable",20],["🏙️","Lix Plaza",25],["🏆","Lix Arena",40]].map(x=>`<div class="tile ${S.level<x[2]?"locked":""}"><div style="font-size:26px">${x[0]}</div><h3>${x[1]}</h3><small>${S.level<x[2]?"Unlock Level ":"Unlocked • Level "}${x[2]}</small></div>`).join("")}</div></section>`,"city")}
function games(){shell(`<section class="card"><div class="title"><h2>🎮 Lix Games</h2><small>Energy ${S.energy}/${S.maxEnergy}</small></div>
<div class="game"><h3>🎯 Lix Target</h3><div class="meta">Hit 8 targets in 25 seconds.</div><button class="btn" onclick="targetGame()">PLAY</button></div>
<div class="game"><h3>🏃 Lix Runner</h3><div class="meta">Tap LEFT / RIGHT to avoid obstacles for 20 seconds.</div><button class="btn" onclick="runnerGame()">PLAY</button></div>
<div class="game"><h3>🪙💣 Lix Catch & Bomb</h3><div class="meta">Catch Coins for 20 seconds. Bombs end the round.</div><button class="btn" onclick="catchGame()">PLAY</button></div></section>`,"games")}
function targetGame(){if(!useEnergy())return;let hits=0,time=25,active=true;function place(){const b=document.getElementById("targetBoard");if(!b||!active)return;const t=document.createElement("button");t.className="target";t.textContent="🎯";t.style.left=Math.random()*80+8+"%";t.style.top=Math.random()*72+8+"%";t.onclick=()=>{hits++;t.remove();if(hits>=8)finish(true);else place()};b.appendChild(t)}function finish(win){active=false;clearInterval(iv);if(win){coins(50);addXP(40);S.missions[0].done=true;S.missions[2].done=true;save();toast("🎯 Target complete! +50 Coins +40 XP")}show("games")}shell(`<section class="card"><div class="title"><h2>🎯 Lix Target</h2><b id="tgTime">25</b>s</div><div class="playarea" id="targetBoard"></div><p class="center">Hits: <b id="tgHits">0</b> / 8</p><button class="btn" onclick="show('games')">Exit</button></section>`,"games");const iv=setInterval(()=>{time--;const e=document.getElementById("tgTime");if(e)e.textContent=time;if(time<=0&&!active)clearInterval(iv);else if(time<=0)finish(false)},1000);const observer=setInterval(()=>{const e=document.getElementById("tgHits");if(e)e.textContent=hits;if(!active)clearInterval(observer)},100);place()}
function runnerGame(){if(!useEnergy())return;let t=20,lane=1,alive=true,score=0; shell(`<section class="card"><div class="title"><h2>🏃 Lix Runner</h2><b id="runTime">20</b>s</div><div class="runnerArea" id="runner"><div class="lane"></div><img class="runnerLix" id="rlix" src="lix.png"></div><div class="row"><button class="btn" onclick="moveRunner(-1)">⬅️ LEFT</button><button class="btn" onclick="moveRunner(1)">RIGHT ➡️</button></div><p>Distance: <b id="dist">0</b> m</p></section>`,"games");window.moveRunner=d=>{lane=Math.max(0,Math.min(2,lane+d));document.getElementById("rlix").style.left=(10+lane*35)+"%"};const obs=setInterval(()=>{if(!alive)return;const o=document.createElement("div");o.className="obstacle";o.style.left=(Math.random()*82+8)+"%";document.getElementById("runner")?.appendChild(o);setTimeout(()=>o.remove(),2200)},900);const iv=setInterval(()=>{t--;score+=15;document.getElementById("runTime").textContent=t;document.getElementById("dist").textContent=score;if(t<=0){alive=false;clearInterval(iv);clearInterval(obs);coins(60);addXP(50);S.missions[0].done=true;save();toast("🏃 Run complete! +60 Coins +50 XP");setTimeout(()=>show("games"),500)}},1000)}
function catchGame(){if(!useEnergy())return;let t=20,total=0,alive=true;function spawn(){if(!alive)return;const e=document.createElement("button"),bomb=Math.random()<.18;e.className=bomb?"bomb":"coin";e.textContent=bomb?"💣":"🪙";e.style.left=Math.random()*88+"%";e.style.top=Math.random()*80+"%";e.onclick=()=>{if(bomb){alive=false;cleanup();toast("💣 Bomb! You keep "+total+" Coins");show("games")}else{total+=Math.random()<.2?5:1;e.remove();const x=document.getElementById("ct");if(x)x.textContent=total}};document.getElementById("catch")?.appendChild(e);setTimeout(()=>e.remove(),1500)}function cleanup(){clearInterval(iv);clearInterval(sp);coins(total);addXP(60);S.missions[0].done=true;save()}shell(`<section class="card"><div class="title"><h2>🪙💣 Catch & Bomb</h2><b id="ctTime">20</b>s</div><div class="catchArea" id="catch"></div><p>Collected: <b id="ct">0</b> Coins</p><button class="btn" onclick="show('games')">Exit</button></section>`,"games");const sp=setInterval(spawn,550),iv=setInterval(()=>{t--;document.getElementById("ctTime").textContent=t;if(t<=0&&alive){alive=false;cleanup();toast("🪙 Round complete! +"+total+" Coins");setTimeout(()=>show("games"),500)}},1000)}
function pets(){const ready=Date.now()-S.petPlayed>=86400000;shell(`<section class="card"><div class="title"><h2>🐾 Lix Stable</h2><small>Pet Level ${S.pet}</small></div><div class="tile"><div style="font-size:56px">🐶</div><h3>Happy Dog</h3><small>Develop your pet with food and toys.</small></div></section><section class="card"><div class="title"><h2>🛒 Pet Shop</h2></div><div class="grid"><div class="tile"><h3>🍖 Basic Food</h3><small>20 Coins</small><br><button class="btn" onclick="petBuy(20)">Buy</button></div><div class="tile"><h3>⚽ Ball</h3><small>100 Coins</small><br><button class="btn" onclick="petBuy(100)">Buy</button></div></div></section><section class="card"><div class="title"><h2>❤️ Daily Play</h2><small>${ready?"Ready":"once / 24h"}</small></div><p>Feed + Play → Happy Pet → +1 Energy once per 24h + Pet XP once per 24h.</p><button class="btn" style="width:100%" ${ready?"":"disabled"} onclick="petPlay()">${ready?"PLAY WITH PET":"PLAY AGAIN TOMORROW"}</button></section>`,"pets")}
function petBuy(n){if(!spend(n))return;S.pet=Math.min(10,S.pet+1);save();toast("🐶 Pet Level "+S.pet);show("pets")}
function petPlay(){if(Date.now()-S.petPlayed<86400000)return;S.petPlayed=Date.now();S.energy=Math.min(S.maxEnergy,S.energy+1);addXP(25+S.pet*5);S.missions[3].done=true;save();toast("❤️ Happy Pet! +1 Energy");show("pets")}
function spin(){if(Date.now()-S.lastSpin<86400000){toast("🎡 Spin available once every 24h");return}const rewards=[20,30,50,75,100,1];const r=rewards[Math.floor(Math.random()*rewards.length)];S.lastSpin=Date.now();if(r===1)S.tickets++;else S.coins+=r;save();toast(r===1?"🎟️ +1 Ticket!":"🎡 +"+r+" Coins!");show("more")}
function more(){const ready=Date.now()-S.lastSpin>=86400000;shell(`<section class="card"><div class="title"><h2>☰ More</h2></div><div class="tile center"><h3>🎡 Daily Spin</h3><div class="spin" id="wheel"></div><button class="btn" onclick="spin()" ${ready?"":"disabled"}>${ready?"SPIN NOW":"READY TOMORROW"}</button><p><small>One spin every 24 hours.</small></p></div><div class="tile"><h3>🏆 Leaderboards</h3><small>${S.level>=10?"Unlocked":"Unlock at Player Level 10."}</small></div><div class="tile"><h3>👤 Player ID</h3><small>LIX-${String(S.level).padStart(2,"0")}-${String(S.coins).padStart(4,"0")}</small></div></section>`,"more")}
function render(){show("home")}render();