const KEY="lixcity_v06",OLD="lixcity_v05";const D={level:1,xp:0,coins:250,tickets:0,energy:10,maxEnergy:10,house:1,pet:1,petPlayed:0,lastSpin:0,game:{target:1,runner:1,catch:1},missions:[{t:"Play any game",xp:40,done:false},{t:"Earn 50 Coins",xp:40,done:false},{t:"Finish Lix Target",xp:50,done:false},{t:"Feed & play with your Pet",xp:50,done:false},{t:"Visit your City",xp:30,done:false}],city:{x:43,y:48,pet:false}};let S=JSON.parse(localStorage.getItem(KEY)||"null");if(!S){const o=JSON.parse(localStorage.getItem(OLD)||"null");S=o?{...structuredClone(D),...o,city:{x:43,y:48,pet:false}}:structuredClone(D);save()}function save(){localStorage.setItem(KEY,JSON.stringify(S))}function need(l){return Math.round(500*l+300*Math.pow(Math.max(0,l-1),1.35))}function addXP(n){S.xp+=n;while(S.xp>=need(S.level)){S.xp-=need(S.level);S.level++;S.house=S.level;toast("🏠 House / Player Level "+S.level+"!")}save();render()}function spend(n){if(S.coins<n){toast("Not enough Coins");return false}S.coins-=n;save();return true}function energy(){if(S.energy<1){toast("⚡ No Energy");return false}S.energy--;save();render();return true}function coins(n){S.coins+=n;save();render()}function toast(t){let e=document.querySelector(".toast");if(!e)return;e.textContent=t;e.style.display="block";clearTimeout(window.tt);window.tt=setTimeout(()=>e.style.display="none",1800)}function nav(a){return`<div class="nav"><div class="navin"><button class="${a==="home"?"active":""}" onclick="show('home')"><b>🏠</b>Home</button><button class="${a==="city"?"active":""}" onclick="show('city')"><b>🏙️</b>City</button><button class="${a==="games"?"active":""}" onclick="show('games')"><b>🎮</b>Games</button><button class="${a==="pets"?"active":""}" onclick="show('pets')"><b>🐾</b>Pets</button><button class="${a==="more"?"active":""}" onclick="show('more')"><b>☰</b>More</button></div></div>`}function shell(c,a){document.getElementById("app").innerHTML=`<header class="top"><div class="brand"><img src="cellix-logo.webp"></div><div class="stats"><span>⭐ ${S.xp}</span><span><img class="coin-icon" src="coin.png"> ${S.coins}</span><span>⚡ ${S.energy}/${S.maxEnergy}</span></div></header><main class="wrap">${c}</main>${nav(a)}<div class="toast"></div>`}function show(p){({home,city,games,pets,more}[p])()}
function home(){let n=need(S.level),pct=Math.min(100,S.xp/n*100);shell(`<section class="hero"><div><small>LIX CITY</small><h1>Welcome to your city</h1><p>PLAY → EARN → BUILD → PROGRESS</p><div class="level">HOUSE / PLAYER LEVEL <strong>${S.level}</strong></div></div><img src="lix.png"></section><section class="card"><div class="title"><h2>🏙️ My City</h2><small>House Lv. ${S.house}</small></div><div class="grid"><div class="tile"><div>🏠</div><h3>Lix House</h3><small>Level ${S.house}</small></div><div class="tile ${S.level<2?"locked":""}"><div>🎮</div><h3>Game Center</h3><small>${S.level<2?"Unlock Lv. 2":"Available"}</small></div><div class="tile ${S.level<4?"locked":""}"><div>🏪</div><h3>Cellix Store</h3><small>${S.level<4?"Unlock Lv. 4":"Available"}</small></div><div class="tile"><div>🛣️</div><h3>City Road</h3><small>Starting area</small></div></div></section><section class="card"><div class="title"><h2>📈 Progress</h2><b>Lv. ${S.level}</b></div><div class="progress"><div class="bar" style="width:${pct}%"></div></div><p>${S.xp} / ${n} XP to next level</p><div class="row"><button class="btn" onclick="show('games')">🎮 Play</button><button class="btn alt" onclick="show('city')">🏙️ Enter City</button></div></section><section class="card"><div class="title"><h2>📋 Daily Missions</h2><small>5 missions</small></div>${S.missions.map((m,i)=>`<div class="mission"><span>${m.done?"✅":"⬜"} ${m.t} <small>+${m.xp} XP</small></span>${m.done?"":"<button class='btn alt' onclick='claimMission("+i+")'>Claim</button>"}</div>`).join("")}</section>`,"home")}
function claimMission(i){if(S.missions[i].done)return;S.missions[i].done=true;addXP(S.missions[i].xp);toast("Mission complete! +"+S.missions[i].xp+" XP")}
function city(){
  let x=S.city?.x??43, y=S.city?.y??48;
  const lx=Math.max(100,Math.min(820, x*9.2)), ly=Math.max(120,Math.min(650,y*7.2));
  shell(`<section class="card"><div class="title"><h2>🏙️ Lix City</h2><small>House Lv. ${S.house}</small></div>
  <div class="city-viewport" id="cityViewport"><div class="city-world" id="cityWorld">
    <div class="road-h"></div><div class="road-v"></div>
    <div class="city-building b-house"><div class="roof"></div><div class="front"><span class="window" style="left:25px;top:34px"></span><span class="window" style="right:25px;top:34px"></span><span class="door"></span><div class="label">🏠 Lix House • Lv.${S.house}</div></div></div>
    <div class="city-building b-center ${S.level<2?"locked-building":""}"><div class="roof"></div><div class="front"><span class="window" style="left:25px;top:34px"></span><span class="window" style="right:25px;top:34px"></span><span class="door"></span><div class="label">🎮 Game Center ${S.level<2?"🔒":"OPEN"}</div></div></div>
    <div class="city-building b-store ${S.level<4?"locked-building":""}"><div class="roof"></div><div class="front"><span class="window" style="left:25px;top:34px"></span><span class="window" style="right:25px;top:34px"></span><span class="door"></span><div class="label">🏪 Cellix Store ${S.level<4?"• Lv.4":"OPEN"}</div></div></div>
    <div class="city-building b-park ${S.level<7?"locked-building":""}"><div class="roof"></div><div class="front"><span class="window" style="left:25px;top:34px"></span><span class="window" style="right:25px;top:34px"></span><span class="door"></span><div class="label">🌳 Lix Park ${S.level<7?"• Lv.7":"OPEN"}</div></div></div>
    <div class="city-building b-energy ${S.level<8?"locked-building":""}"><div class="roof"></div><div class="front"><span class="window" style="left:25px;top:34px"></span><span class="window" style="right:25px;top:34px"></span><span class="door"></span><div class="label">⚡ Energy Station ${S.level<8?"• Lv.8":"OPEN"}</div></div></div>
    <span class="world-tree wt1">🌳</span><span class="world-tree wt2">🌲</span><span class="world-tree wt3">🌳</span><span class="world-tree wt4">🌲</span><span class="world-tree wt5">🌳</span>
    <span class="world-lamp wl1">💡</span><span class="world-lamp wl2">💡</span><span class="world-lamp wl3">💡</span><span class="world-lamp wl4">💡</span>
    <span class="world-sign ws1">LIX DISTRICT</span><span class="world-sign ws2">CITY ROAD</span>
    <img class="world-coin wc1" src="coin.png" onclick="collectCityCoin(this,5)" alt="Coin">
    <img class="world-coin wc2" src="coin.png" onclick="collectCityCoin(this,5)" alt="Coin">
    <img class="world-coin wc3" src="coin.png" onclick="collectCityCoin(this,5)" alt="Coin">
    <img class="world-coin wc4" src="coin.png" onclick="collectCityCoin(this,5)" alt="Coin">
    <img class="world-coin wc5" src="coin.png" onclick="collectCityCoin(this,5)" alt="Coin">
    <img id="worldLix" class="world-lix" src="lix.png" style="left:${lx}px;top:${ly}px" alt="Lix">
    ${S.city?.pet?'<span id="worldPet" class="world-pet" style="left:'+(lx+75)+'px;top:'+(ly+60)+'px">🐶</span>':""}
  </div></div>
  <div class="city-scroll-hint">↕️ اسحب الخريطة لتستكشف المدينة</div>
  <div class="city-controls"><button class="round" onclick="moveLix(-3,0)">⬅</button><button class="round" onclick="moveLix(0,-3)">⬆</button><button class="round" onclick="moveLix(0,3)">⬇</button><button class="round" onclick="moveLix(3,0)">➡</button></div>
  <div class="city-note">🪙 الـCoins بالمدينة هي نفس <b>coin.png</b> الرسمي. اضغط على أي Coin تجمعه وتربح 5 Coins.</div></section>
  <section class="card"><div class="title"><h2>🔓 Building Roadmap</h2></div><div class="grid">${[["🏠","Lix House",1],["🎮","Game Center",2],["🏪","Cellix Store",4],["🌳","Lix Park",7],["⚡","Energy Station",8],["🛠️","Lix Workshop",12],["🏬","Lix Market",15],["🎨","Lix Studio",18],["🐾","Lix Stable",20],["🏙️","Lix Plaza",25],["🏆","Lix Arena",40]].map(a=>`<div class="tile ${S.level<a[2]?"locked":""}"><div style="font-size:26px">${a[0]}</div><h3>${a[1]}</h3><small>${S.level<a[2]?"Unlock Level ":"Unlocked • Level "}${a[2]}</small></div>`).join("")}</div></section>`,"city");
}
function collectCityCoin(el,n){
  if(!el || el.dataset.collected==="1") return;
  el.dataset.collected="1";
  el.style.transition="transform .25s, opacity .25s";
  el.style.transform="scale(1.7) translateY(-12px)";
  el.style.opacity="0";
  coins(n);
  setTimeout(()=>el.remove(),260);
  toast("🪙 +"+n+" Coins");
}
function moveLix(dx,dy){
  S.city=S.city||{x:43,y:48,pet:false};
  S.city.x=Math.max(10,Math.min(88,S.city.x+dx));
  S.city.y=Math.max(10,Math.min(88,S.city.y+dy));
  save();
  const e=document.getElementById("worldLix");
  if(e){
    const px=Math.max(100,Math.min(820,S.city.x*9.2)), py=Math.max(120,Math.min(650,S.city.y*7.2));
    e.style.left=px+"px"; e.style.top=py+"px";
    e.style.transform="translateY(-5px)";
    setTimeout(()=>e.style.transform="",180);
    const p=document.getElementById("worldPet");
    if(p){p.style.left=(px+75)+"px";p.style.top=(py+60)+"px";}
    const vp=document.getElementById("cityViewport");
    if(vp){vp.scrollTo({left:Math.max(0,px-220),top:Math.max(0,py-180),behavior:"smooth"});}
  }
}
function games(){shell(`<section class="card"><div class="title"><h2>🎮 Lix Games</h2><small>Energy ${S.energy}/${S.maxEnergy}</small></div><div class="game"><h3>🎯 Lix Target</h3><div class="muted">Hit 8 targets in 25 seconds.</div><button class="btn" onclick="targetGame()">PLAY</button></div><div class="game"><h3>🏃 Lix Runner</h3><div class="muted">Move Lix and avoid obstacles for 20 seconds.</div><button class="btn" onclick="runnerGame()">PLAY</button></div><div class="game"><h3>🪙💣 Lix Catch & Bomb</h3><div class="muted">Catch Coins for 20 seconds.</div><button class="btn" onclick="catchGame()">PLAY</button></div></section>`,"games")}
function targetGame(){if(!energy())return;let h=0,t=25,active=true;function end(w){if(!active)return;active=false;clearInterval(iv);if(w){coins(50);addXP(40);S.missions[0].done=true;S.missions[2].done=true;save();toast("🎯 +50 Coins +40 XP")}else toast("Time's up!");setTimeout(()=>show("games"),400)}function place(){if(!active)return;let b=document.getElementById("targetBoard");if(!b)return;let e=document.createElement("button");e.className="target";e.textContent="🎯";e.style.left=Math.random()*80+8+"%";e.style.top=Math.random()*72+8+"%";e.onclick=()=>{h++;e.remove();document.getElementById("tgHits").textContent=h;h>=8?end(true):place()};b.appendChild(e)}shell(`<section class="card"><div class="title"><h2>🎯 Lix Target</h2><b id="tgTime">25</b>s</div><div class="playarea" id="targetBoard"></div><p class="center">Hits: <b id="tgHits">0</b> / 8</p><button class="btn alt" onclick="show('games')">Exit</button></section>`,"games");let iv=setInterval(()=>{t--;document.getElementById("tgTime").textContent=t;if(t<=0)end(false)},1000);place()}
function runnerGame(){if(!energy())return;let t=20,l=0,alive=true,d=0;function end(){if(!alive)return;alive=false;clearInterval(iv);clearInterval(obs);coins(60);addXP(50);S.missions[0].done=true;save();toast("🏃 +60 Coins +50 XP");setTimeout(()=>show("games"),400)}shell(`<section class="card"><div class="title"><h2>🏃 Lix Runner</h2><b id="rt">20</b>s</div><div class="runnerArea" id="runner"><div class="lane"></div><img class="runnerLix" id="rlix" src="lix.png"></div><div class="row"><button class="btn" onclick="moveRunner(-1)">⬅️ LEFT</button><button class="btn" onclick="moveRunner(1)">RIGHT ➡️</button></div><p>Distance: <b id="dist">0</b> m</p></section>`,"games");window.moveRunner=z=>{l=Math.max(0,Math.min(2,l+z));document.getElementById("rlix").style.left=(10+l*35)+"%"};let obs=setInterval(()=>{let o=document.createElement("div");o.className="obstacle";o.style.left=(8+Math.floor(Math.random()*3)*35)+"%";document.getElementById("runner")?.appendChild(o);setTimeout(()=>o.remove(),2200)},850);let iv=setInterval(()=>{t--;d+=15;document.getElementById("rt").textContent=t;document.getElementById("dist").textContent=d;if(t<=0)end()},1000)}
function catchGame(){if(!energy())return;let t=20,total=0,alive=true;function cleanup(){clearInterval(iv);clearInterval(sp);coins(total);addXP(60);S.missions[0].done=true;save()}function end(msg){if(!alive)return;alive=false;cleanup();toast(msg);setTimeout(()=>show("games"),500)}function spawn(){if(!alive)return;let e=document.createElement("button"),bomb=Math.random()<.18;e.className="fall "+(bomb?"":"coin-img");if(bomb)e.textContent="💣";else e.innerHTML='<img src="coin.png" style="width:42px;height:42px;object-fit:contain">' ;e.style.left=Math.random()*88+"%";e.style.top=Math.random()*80+"%";e.onclick=()=>bomb?end("💣 Bomb! You keep "+total+" Coins"):(total+=Math.random()<.2?5:1,e.remove(),document.getElementById("ct").textContent=total);document.getElementById("catch")?.appendChild(e);setTimeout(()=>e.remove(),1500)}shell(`<section class="card"><div class="title"><h2>🪙💣 Catch & Bomb</h2><b id="ctt">20</b>s</div><div class="catchArea" id="catch"></div><p><img class="coin-icon small" src="coin.png"> Collected: <b id="ct">0</b> Coins</p><button class="btn alt" onclick="show('games')">Exit</button></section>`,"games");let sp=setInterval(spawn,500),iv=setInterval(()=>{t--;document.getElementById("ctt").textContent=t;if(t<=0)end("🪙 Round complete! +"+total+" Coins")},1000)}
function pets(){let ready=Date.now()-S.petPlayed>=86400000;shell(`<section class="card"><div class="title"><h2>🐾 Lix Stable</h2><small>Pet Level ${S.pet}</small></div><div class="tile"><div style="font-size:56px">🐶</div><h3>Happy Dog</h3><small>Develop your pet with food and toys.</small></div></section><section class="card"><div class="grid"><div class="tile"><h3>🍖 Basic Food</h3><small>20 Coins</small><br><button class="btn" onclick="petBuy(20)">Buy</button></div><div class="tile"><h3>⚽ Ball</h3><small>100 Coins</small><br><button class="btn" onclick="petBuy(100)">Buy</button></div></div></section><section class="card"><div class="title"><h2>❤️ Daily Play</h2><small>${ready?"Ready":"once / 24h"}</small></div><p>Happy Pet → +1 Energy once per 24h + Pet XP once per 24h.</p><button class="btn" ${ready?"":"disabled"} onclick="petPlay()">${ready?"PLAY WITH PET":"PLAY AGAIN TOMORROW"}</button><button class="btn alt" onclick="takePetToCity()" style="margin-left:8px">🏙️ Pet in City</button></section>`,"pets")}
function petBuy(n){if(!spend(n))return;S.pet=Math.min(10,S.pet+1);save();toast("🐶 Pet Level "+S.pet);show("pets")}function petPlay(){if(Date.now()-S.petPlayed<86400000)return;S.petPlayed=Date.now();S.energy=Math.min(S.maxEnergy,S.energy+1);addXP(25+S.pet*5);S.missions[3].done=true;save();toast("❤️ Happy Pet! +1 Energy");show("pets")}function takePetToCity(){S.city=S.city||{};S.city.pet=true;save();toast("🐶 Your pet joined Lix in the city!");show("city")}
function spin(){if(Date.now()-S.lastSpin<86400000){toast("🎡 Spin available once every 24h");return}let r=[20,30,50,75,100,1][Math.floor(Math.random()*6)];S.lastSpin=Date.now();r===1?S.tickets++:S.coins+=r;save();toast(r===1?"🎟️ +1 Ticket!":"🎡 +"+r+" Coins!");show("more")}function more(){let ready=Date.now()-S.lastSpin>=86400000;shell(`<section class="card"><div class="title"><h2>☰ More</h2></div><div class="tile center"><h3>🎡 Daily Spin</h3><div class="spin"></div><button class="btn" onclick="spin()" ${ready?"":"disabled"}>${ready?"SPIN NOW":"READY TOMORROW"}</button><p><small>One spin every 24 hours.</small></p></div><div class="tile"><h3>🏆 Leaderboards</h3><small>${S.level>=10?"Unlocked":"Unlock at Player Level 10."}</small></div></section>`,"more")}function render(){show("home")}render();