(()=>{
const KEY='lixcity_player_save_v1', K='lixcity_arcade_v26';
const defaults={best:{target:0,runner:0,catch:0},plays:{target:0,runner:0,catch:0},wins:{target:0,runner:0,catch:0},combo:0,totalCoins:0};
const get=()=>{try{return {...defaults,...JSON.parse(localStorage.getItem(K)||'{}')}}catch{return {...defaults}}};
const save=(x)=>localStorage.setItem(K,JSON.stringify(x));
const state=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return {}}};
function grant(coins,xp){let s=state();s.coins=Math.max(0,(s.coins||0)+coins);s.xp=Math.max(0,(s.xp||0)+xp);s.energy=Math.max(0,(s.energy||0)-1);if(window.normalizeState){try{s=window.normalizeState(s)}catch{}}localStorage.setItem(KEY,JSON.stringify(s));return s}
function canPlay(){let s=state();if((s.energy||0)<1){alert('⚡ No Energy. Come back when Energy regenerates.');return false}return true}
function close(){document.getElementById('v26Arcade')?.remove()}
function shell(title,body){close();let d=document.createElement('div');d.id='v26Arcade';d.innerHTML=`<div class="v26shade"><div class="v26modal"><div class="v26head"><b>🎮 ${title}</b><button id="v26x">✕</button></div>${body}</div></div>`;document.body.appendChild(d);d.querySelector('#v26x').onclick=close}
function home(){let d=get();shell('LIX ARCADE',`<div class="v26hero"><img src="lix.png"><div><h2>Play • Skill • Earn</h2><p>Three fast challenges. Every round costs 1 Energy.</p></div></div><div class="v26games"><button data-g="target">🎯<b>Lix Target</b><small>Accuracy • Combo</small></button><button data-g="runner">🏃<b>Lix Runner</b><small>Distance • Speed</small></button><button data-g="catch">🪙<b>Catch & Bomb</b><small>Coins • Risk</small></button></div><div class="v26stats"><b>Best Target: ${d.best.target}</b><b>Best Runner: ${d.best.runner}m</b><b>Best Catch: ${d.best.catch}</b></div>`);document.querySelectorAll('[data-g]').forEach(b=>b.onclick=()=>start(b.dataset.g))}
function end(type,score,coins,xp,win){let d=get();d.plays[type]++;if(win)d.wins[type]++;d.best[type]=Math.max(d.best[type],score);d.totalCoins+=coins;save(d);grant(coins,xp);let s=state();let combo=(d.combo||0)+(win?1:-1);d.combo=Math.max(0,combo);save(d);shell('ROUND COMPLETE',`<div class="v26result"><div class="v26big">${win?'🏆':'⚡'}</div><h2>${win?'Great run!':'Round finished'}</h2><p>Score <b>${score}</b></p><p>🪙 +${coins} Coins &nbsp; ⭐ +${xp} XP &nbsp; ⚡ -1 Energy</p><button class="v26btn" id="again">PLAY AGAIN</button><button class="v26btn alt" id="back">ARCADE</button></div>`);document.getElementById('again').onclick=()=>start(type);document.getElementById('back').onclick=home}
function start(type){if(!canPlay())return; if(type==='target')target();if(type==='runner')runner();if(type==='catch')catcher()}
function target(){let n=0,time=25,goal=15,combo=0,active=true;shell('LIX TARGET',`<div class="v26bar"><b>Targets ${goal}</b><b id="vt">25s</b></div><div class="targetzone" id="tz"></div><p>Hits: <b id="vh">0</b> • Combo: <b id="vc">0</b></p>`);let z=document.getElementById('tz');let spawn=()=>{if(!active)return;let e=document.createElement('button');e.className='targetdot';e.style.left=(5+Math.random()*86)+'%';e.style.top=(5+Math.random()*78)+'%';e.onclick=()=>{n++;combo++;document.getElementById('vh').textContent=n;document.getElementById('vc').textContent=combo;e.remove();if(n>=goal)finish()};z.appendChild(e);setTimeout(()=>e.remove(),1100)};let sp=setInterval(spawn,650),iv=setInterval(()=>{time--;document.getElementById('vt').textContent=time+'s';if(time<=0)finish()},1000);function finish(){if(!active)return;active=false;clearInterval(sp);clearInterval(iv);let win=n>=goal;end('target',n,win?Math.min(80,25+n*2):0,win?45:5,win)}}
function runner(){let t=30,dist=0,score=0,lane=1,active=true;shell('LIX RUNNER',`<div class="v26bar"><b>Distance <span id="vd">0</span>m</b><b id="vr">30s</b></div><div class="runzone" id="rz"><img src="lix.png" id="vrl"></div><div class="v26controls"><button id="vl">⬅️</button><button id="vrb">➡️</button></div>`);let r=document.getElementById('vrl');const move=x=>{lane=Math.max(0,Math.min(2,lane+x));r.style.left=(12+lane*35)+'%'};document.getElementById('vl').onclick=()=>move(-1);document.getElementById('vrb').onclick=()=>move(1);let obs=setInterval(()=>{let o=document.createElement('i');o.className='obstacle26';o.style.left=(10+Math.floor(Math.random()*3)*35)+'%';document.getElementById('rz').appendChild(o);setTimeout(()=>{if(o.isConnected){if(Math.abs(parseFloat(r.style.left)-parseFloat(o.style.left))<15){active=false;clearInterval(obs);clearInterval(iv);end('runner',dist,0,5,false)}o.remove()}},1300)},700);let iv=setInterval(()=>{if(!active)return;t--;dist+=20;score=dist;document.getElementById('vd').textContent=dist;document.getElementById('vr').textContent=t+'s';if(t<=0){active=false;clearInterval(obs);clearInterval(iv);let win=dist>=500;end('runner',dist,win?70:0,win?55:5,win)}},1000)}
function catcher(){let t=35,total=0,active=true;shell('CATCH & BOMB',`<div class="v26bar"><b>🪙 <span id="vcash">0</span></b><b id="vct">35s</b></div><div class="catchzone" id="cz"></div><p>Catch coins. Avoid bombs.</p>`);let z=document.getElementById('cz');let sp=setInterval(()=>{if(!active)return;let e=document.createElement('button'),bomb=Math.random()<.16;e.className=bomb?'bomb26':'coin26';e.innerHTML=bomb?'💣':'<img src="coin.png">';e.style.left=Math.random()*88+'%';e.style.top=Math.random()*82+'%';e.onclick=()=>{if(bomb){active=false;clearInterval(sp);clearInterval(iv);end('catch',total,total,10,false)}else{total+=Math.random()<.15?10:1;document.getElementById('vcash').textContent=total;e.remove()}};z.appendChild(e);setTimeout(()=>e.remove(),1300)},420);let iv=setInterval(()=>{t--;document.getElementById('vct').textContent=t+'s';if(t<=0){active=false;clearInterval(sp);clearInterval(iv);let win=total>=50;end('catch',total,total,win?60:10,win)}},1000)}
function mount(){let b=document.createElement('button');b.id='v26ArcadeBtn';b.innerHTML='🎮 <span>LIX ARCADE</span>';b.onclick=home;document.body.appendChild(b)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();
})();