(()=>{'use strict';
const KEY='lixcity_v24_content';let tab='overview',opened=false,config=null;
const catalog=[['hoodie','Blue Hoodie','top',120,1],['jacket','City Jacket','top',250,4],['sport','Runner Jersey','top',360,8],['royal','Royal Jacket','top',700,15],['shoes','Light Shoes','feet',100,1],['boots','City Boots','feet',240,5],['speed','Speed Sneakers','feet',450,10],['cap','Blue Cap','head',90,1],['visor','Arcade Visor','head',230,6],['crown','City Crown','head',900,20],['glasses','Star Glasses','face',180,3],['shades','Night Shades','face',340,9],['bag','Mini Backpack','back',210,4],['wings','Light Wings','back',800,18],['watch','Digital Watch','accessory',160,2],['badge','City Badge','accessory',310,7]];
const furniture=[['chair','Cozy Chair',90,1],['lamp','Blue Lamp',130,2],['plant','House Plant',160,3],['desk','Work Desk',300,6],['sofa','Cloud Sofa',480,10],['arcade','Arcade Machine',750,15],['trophy','Trophy Shelf',1100,20]];
const goals=[['g1','Play 3 games',s=>s.plays>=3,80],['g2','Own 3 wardrobe items',s=>s.owned.length>=3,100],['g3','Decorate your house',s=>s.furniture.length>=1,60],['g4','Play 10 games',s=>s.plays>=10,160],['g5','Own 2 pets',s=>s.pets.length>=2,150],['g6','Reach player level 10',()=>S.level>=10,250]];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function state(){let x={};try{x=JSON.parse(localStorage.getItem(KEY)||'{}')||{}}catch(e){}return {owned:Array.isArray(x.owned)?x.owned:[],equipped:x.equipped&&typeof x.equipped==='object'?x.equipped:{},furniture:Array.isArray(x.furniture)?x.furniture:[],pets:Array.isArray(x.pets)?x.pets:['dog'],activePet:x.activePet||'dog',petSupplies:x.petSupplies||{food:0,ball:0},petLastPlay:Number(x.petLastPlay)||0,plays:Number(x.plays)||0,claimed:Array.isArray(x.claimed)?x.claimed:[],eventClaimed:!!x.eventClaimed};}
let data=state();const persist=()=>{localStorage.setItem(KEY,JSON.stringify(data));};
function player(){try{return typeof S!=='undefined'&&S&&typeof S==='object'?S:null}catch(e){return null}}
function sync(){const p=player();if(!p)return;data.plays=Math.max(data.plays,Number(p.stats?.plays||0),Number(p.gameStats?.plays||0));persist()}
function notify(s){let e=document.getElementById('lix24notice');if(e){e.textContent=s;e.hidden=false;setTimeout(()=>{e.hidden=true},2600)}}
function purchase(cost,fn){const p=player();if(!p)return notify('Game save unavailable');if(p.coins<cost)return notify('Not enough Coins');p.coins-=cost;fn();persist();if(typeof save==='function')save();notify('Purchased!');draw()}
function xp(n){if(typeof addXP==='function')addXP(n);else{const p=player();if(p){p.xp+=n;if(typeof save==='function')save()}}}
const card=(title,body)=>`<section class="l24card"><h3>${title}</h3>${body}</section>`;
const btn=(label,action,disabled=false)=>`<button class="l24btn" data-action="${action}" ${disabled?'disabled':''}>${label}</button>`;
const petImages={dog:'dog.png',cat:'cat.png',horse:'horse.png'};
function overview(){const p=player()||{};return card('YOUR PROGRESS',`<div class="l24stats"><span>🏠 Level <b>${p.level||1}</b></span><span><img src="coin.png" alt="Coin"> <b>${p.coins||0}</b></span><span>⚡ <b>${p.energy||0}/${p.maxEnergy||10}</b></span><span>🎟️ <b>${p.tickets||0}</b></span></div><div class="l24preview"><img src="lix.png" alt="Lix"><div><b>${esc(p.nickname||'Lix Player')}</b><p>${data.owned.length} outfits · ${data.furniture.length} furniture · ${data.pets.length} pets</p>${btn('OPEN WARDROBE','tab:wardrobe')}</div></div>`)+card('QUICK ACCESS',`<div class="l24grid">${[['🎮 Games','games'],['🏙️ City','city'],['🏠 House','house'],['📋 Missions','missions'],['🎡 Daily Spin','home'],['🐾 Stable','pets']].map(([n,r])=>btn(n,'route:'+r)).join('')}</div>`)+card('SAVE SAFETY',`<p>Browser-only prototype save. Export a backup before changing devices or clearing browser data.</p>${btn('EXPORT SAVE','export')} ${btn('IMPORT SAVE','import')}`)}
function wardrobe(){return card('MIX & MATCH LIX',`<div class="l24preview"><img src="lix.png" alt="Original Lix"><div><b>Equipped</b><p>${Object.entries(data.equipped).map(([k,v])=>esc(k)+': '+esc(catalog.find(x=>x[0]===v)?.[1]||v)).join('<br>')||'Original Lix — no accessories equipped'}</p><small>Items are shown in inventory; visual overlays require individual transparent outfit artwork. Original Lix is never altered.</small></div></div><div class="l24grid">${catalog.map(([id,name,slot,cost,lv])=>{const owned=data.owned.includes(id),on=data.equipped[slot]===id,locked=(player()?.level||1)<lv;return `<div class="l24item"><b>${esc(name)}</b><small>${slot} · Level ${lv}</small>${btn(locked?'LOCKED':on?'UNEQUIP':owned?'EQUIP':cost+' Coins','wear:'+id,locked)}</div>`}).join('')}</div>`)}
function house(){return card('HOUSE FURNITURE',`<p>Owned furniture is stored separately and stays after navigation.</p><div class="l24grid">${furniture.map(([id,name,cost,lv])=>{const owned=data.furniture.includes(id),locked=(player()?.level||1)<lv;return `<div class="l24item"><b>${esc(name)}</b><small>Unlock Level ${lv}</small>${btn(owned?'OWNED':locked?'LOCKED':cost+' Coins','furniture:'+id,owned||locked)}</div>`}).join('')}</div>`)+card('HOUSE PROGRESSION',`<p>Player Level and House Level advance together. Your existing house and city remain available.</p>${btn('ENTER HOUSE','route:house')}`)}
function pets(){const lv=player()?.level||1;return card('LIX STABLE · LEVEL 20',`<p>${lv<20?'Stable unlocks at Player Level 20.':'Choose one companion to follow Lix.'}</p><div class="l24grid">${Object.entries(petImages).map(([id,img])=>`<div class="l24item"><img class="l24pet" src="${img}" alt="${id}"><b>${id.toUpperCase()}</b>${btn(data.activePet===id?'ACTIVE':data.pets.includes(id)?'ACTIVATE':'ADOPT · 1500 Coins','pet:'+id,lv<20)}</div>`).join('')}</div>`)+`<p>Food: ${data.petSupplies.food} · Balls: ${data.petSupplies.ball}</p>${btn('BUY FOOD · 20','food',lv<20)} ${btn('BUY BALL · 100','ball',lv<20)} ${btn('DAILY PLAY · +1 ENERGY','petplay',lv<20)}`}
function goalsPage(){sync();return card('CITY ACHIEVEMENTS',goals.map(([id,name,test,reward])=>{const done=data.claimed.includes(id),ready=test(data);return `<div class="l24line"><span>${done?'✅':ready?'🏆':'⬜'} ${name}<small>+${reward} XP · one-time</small></span>${btn(done?'CLAIMED':ready?'CLAIM':'IN PROGRESS','goal:'+id,done||!ready)}</div>`}).join(''))+card('MONTHLY EVENTS',`<p>Event system is a local prototype; real events and prizes require an admin-managed backend.</p>${btn('VIEW EVENTS','route:events')}`)}
function shop(){const items=(config?.enabled?config.products:[])||[];return card('CELLIX STORE',items.filter(x=>x.active&&/^https:\/\//i.test(x.url||'')).length?items.filter(x=>x.active&&/^https:\/\//i.test(x.url||'')).map(x=>`<div class="l24line"><span><b>${esc(x.name)}</b><small>${esc(x.provider)} ${esc(x.price)}</small></span>${btn('BUY NOW','shop:'+esc(x.id))}</div>`).join(''):'<p>No active products yet. The owner sets links in shop-config.json; players cannot edit them.</p>')+card('IMPORTANT',`<p>Store links open an external website. Coins and Tickets are in-game currencies, not real money.</p>`)}
function draw(){const el=document.getElementById('lix24panel');if(!el||!opened)return;const names={overview:'Dashboard',wardrobe:'Wardrobe',house:'House',pets:'Pets',goals:'Goals',shop:'Cellix Store'};el.innerHTML=`<div class="l24head"><b>LIX CITY <small>MEGA v2.4</small></b><button class="l24close" data-action="close" aria-label="Close">×</button></div><nav class="l24tabs">${Object.entries(names).map(([id,n])=>`<button class="${tab===id?'selected':''}" data-action="tab:${id}">${n}</button>`).join('')}</nav><div class="l24body">${({overview,wardrobe,house,pets,goals,shop}[tab]||overview)()}</div><div id="lix24notice" class="l24notice" hidden></div>`}
function act(a){const [kind,id]=a.split(':');const p=player();if(kind==='close'){opened=false;document.getElementById('lix24panel').hidden=true;return}if(kind==='tab'){tab=id;draw();return}if(kind==='route'){opened=false;document.getElementById('lix24panel').hidden=true;try{if(id==='house'&&window.LixHouse?.open)window.LixHouse.open();else if(typeof show==='function')show(id)}catch(e){notify('Section not available')}return}if(kind==='wear'){const item=catalog.find(x=>x[0]===id);if(!item)return;if(data.owned.includes(id)){if(data.equipped[item[2]]===id)delete data.equipped[item[2]];else data.equipped[item[2]]=id;persist();draw()}else purchase(item[3],()=>{data.owned.push(id);data.equipped[item[2]]=id});return}if(kind==='furniture'){const item=furniture.find(x=>x[0]===id);if(item&&!data.furniture.includes(id))purchase(item[2],()=>data.furniture.push(id));return}if(kind==='pet'){if((p?.level||1)<20)return;if(data.pets.includes(id)){data.activePet=id;persist();draw()}else purchase(1500,()=>{data.pets.push(id);data.activePet=id});return}if(kind==='food'||kind==='ball'){purchase(kind==='food'?20:100,()=>data.petSupplies[kind]++);return}if(kind==='petplay'){if(Date.now()-data.petLastPlay<86400000)return notify('Daily pet play already claimed');if(data.petSupplies.food<1||data.petSupplies.ball<1)return notify('Need 1 Food and 1 Ball');data.petSupplies.food--;data.petSupplies.ball--;data.petLastPlay=Date.now();if(p){p.energy=Math.min(p.maxEnergy||10,(p.energy||0)+1);if(typeof save==='function')save()}persist();xp(25);draw();return}if(kind==='goal'){const g=goals.find(x=>x[0]===id);if(g&&!data.claimed.includes(id)&&g[2](data)){data.claimed.push(id);persist();xp(g[3]);draw()}return}if(kind==='shop'){const item=config?.products?.find(x=>x.id===id&&x.active&&/^https:\/\//i.test(x.url||''));if(item)window.open(item.url,'_blank','noopener,noreferrer');return}if(kind==='export'){const raw={format:'lix-city-backup-v24',date:new Date().toISOString(),game:localStorage.getItem('lixcity_player_save_v1'),content:data};const blob=new Blob([JSON.stringify(raw,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='lix-city-backup.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);return}if(kind==='import'){document.getElementById('lix24file').click()}}
function mount(){if(document.getElementById('lix24open'))return;const b=document.createElement('button');b.id='lix24open';b.textContent='✨ MEGA';b.addEventListener('click',()=>{opened=true;document.getElementById('lix24panel').hidden=false;draw()});document.body.append(b);const el=document.createElement('aside');el.id='lix24panel';el.hidden=true;el.setAttribute('aria-label','Lix City Mega features');el.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(b)act(b.dataset.action)});document.body.append(el);const file=document.createElement('input');file.type='file';file.accept='.json,application/json';file.id='lix24file';file.hidden=true;file.addEventListener('change',async()=>{try{const raw=JSON.parse(await file.files[0].text());if(raw.format!=='lix-city-backup-v24'||!raw.game||!raw.content||!confirm('Replace current browser save with this backup?'))return;const parsed=JSON.parse(raw.game);if(!parsed||typeof parsed.level!=='number'||typeof parsed.coins!=='number')throw Error('Invalid game save');localStorage.setItem('lixcity_player_save_v1',raw.game);localStorage.setItem(KEY,JSON.stringify(raw.content));location.reload()}catch(e){notify('Invalid backup file')}finally{file.value=''}});document.body.append(file);fetch('shop-config.json',{cache:'no-store'}).then(r=>r.ok?r.json():null).then(x=>{config=x;if(opened&&tab==='shop')draw()}).catch(()=>{});}
window.LIX24={open:(t='overview')=>{tab=t;opened=true;document.getElementById('lix24panel').hidden=false;draw()},recordPlay:()=>{data.plays++;persist()}};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();
})();